## Exploring ANES data - alternate approach
## This script produces data similar to that in the "Exploring the ANES"
## script, but with minor changes here and there.
##
## I have tried to keep all variable names consistent between the two versions.


# Preliminaries -----------------------------------------------------------

library(tidyverse)
library(haven)

## load the original version of the data for comparison
load("data/Sorting - 2020 ANES - updated.RData")


## Recode variables based on some predicate function. This
## is primarily used for recoding variables whose values
## fall in certain ranges to NA.
recode <- function(var, pred, to = NA_real_) {
    return(dplyr::case_when(
        is.na(var) ~ NA_real_,
        pred(var) ~ to,
        TRUE ~ as.numeric(var)
    ))
}

## Quick script for reverse coding.
## NOTE: this is assuming the maximum value for the range is observed.
## For the Likert scales used here, with this many observations, that should
## always be safe.
reverse_code <- function(x) {
  m <- max(x, na.rm = TRUE) + 1
  return(abs(x - m))
}

is_negative <- function(x) {
  return(x < 0)
}

# small subset of 2012 ANES used for Mason replications
anes12 <- read_stata("data/anes_timeseries_2012.dta") |> zap_labels()
anes16 <- read_stata("data/anes_timeseries_2016.dta") |> zap_labels()
anes20 <- read_stata("data/anes_timeseries_2020_stata_20220210.dta") |> zap_labels()


# 2020 ANES ---------------------------------------------------------------

anes20 <- anes20 |>
  select(
    id = V200010c,
    panel_id = V160001_orig,
    strata = V200010d,
    weight = V200010a,
    panel_weight = V200011a,
    pid7 = V201231x,
    ideo = V201200,
    gender = V201600,
    race = V201549x,
    ethnicity = V201546,
    rural_identity = V202356,
    evang = V201459,
    military = V201516,
    union = V201544,
    age = V201507x,
    num_guns = V201628,
    class = V202352,
    education = V201511x,
    parental_origin = V201553,
    income = V201617x,
    marital_status = V201508,
    sexual_orientation = V201601,
    num_children = V201567,
    RR_gen = V202301,
    RR_favor = V202300,
    RR_less = V202302,
    RR_try = V202303,
    auth1 = V202266,
    auth2 = V202267,
    auth3 = V202268,
    auth4 = V202269,
    egal1 = V202260,
    egal2 = V202261,
    egal3 = V202262,
    egal4 = V202263,
    sexism1 = V202286x,
    sexism2 = V202290x,
    sexism3 = V202291,
    sexism4 = V202292,
    nat1 = V202270,
    nat2 = V202273x,
    nat3 = V202421,
    nat4 = V202422,
    nat5 = V202423,
    nat6 = V202424,
    mortrad1 = V202264,
    mortrad2 = V202265,
    imp_partisan = V201232,
    imp_place = V202357,
    imp_evang = V201461,
    imp_fund = V201460,
    facebook = V202541a,
    twitter = V202541b,
    instagram = V202541c,
    reddit = V202541d,
    youtube = V202541e,
    snapchat = V202541f,
    tiktok = V202541g,
    sm_other = V202541h,
    fb_political = V202543,
    tw_political = V202545,
    rd_political = V202547,
    colbert = V201630a,
    hannity = V201630b,
    tucker = V201630c,
    maddow = V201630d,
    lawrence = V201630e,
    the_five = V201630f,
    ingraham = V201630g,
    maccallum = V201630h,
    tapper = V201630i,
    anderson = V201630j,
    baier = V201630k,
    cbs_evening = V201630m,
    abc_world = V201630n,
    nbc_nightly = V201630p,
    cuomo = V201630q,
    ncis = V201630r,
    american_idol = V201631a,
    erin_burnett = V201631b,
    sixty_minutes = V201631c,
    twenty_twenty = V201631d,
    dateline = V201631e,
    face_the_nation = V201631f,
    meet_the_press = V201631g,
    cbs_this_morning = V201631h,
    gma = V201631i,
    nbc_today = V201631j,
    fox_and_friends = V201631k,
    morning_joe = V201631m,
    chris_hayes = V201631n,
    brian_williams = V201631p,
    newshour = V201631q,
    snl = V201631r,
    know_senateterm = V201644,
    know_spend = V201645,
    know_house = V201646,
    know_senate = V201647,
    vio_justscale = V201602,
    # NOTE: i would rename this to be more descriptive - it's
    # perceptions of how violent protestors are
    violence = V201432x,
    unrest = V201429,
    fairelec = V202219,
    educ = V201510,
    demsat = V202440,
    compprinc = V201379,
    comp1 = V202409,
    comp2 = V201379,
    community = V202031,
    talk009 = V202009,
    attend013 = V202013,
    attend014 = V202014,
    wear015 = V202015,
    work016 = V202016,
    give017 = V202017,
    give019 = V202019,
    contact030 = V202030,
    # NOTE: (duplicated variable) contact -> contact034
    contact034 = V202034,
    contact036 = V202036,
    give038 = V202038,
    contact040 = V202040,
    # NOTE: join2 and joined025 referred to the same ANES variable
    joined025 = V202025,
    signed026 = V202026,
    bought042 = V202042,
    discuss022 = V202022,
    posted029 = V202029,
    FT_dem = V201156,
    FT_rep = V201157,
    attend_church_ever = V201452,
    attend_church = V201453,
    attend_church_more = V201454,
    bornagain = V201456,
    dem1 = V202440,
    dem2 = V201367,
    dem3 = V201372x,
    abortion = V201336,
    insurance = V201252,
    services = V201246,
    defense = V201249,
    employment = V201255,
    aid_minorities = V201258,
    state = V203001,
    sample_type = V200003,
  ) |>
  # recode negative values and values greater than 90 to NA
  # this is OK to do for age, because age is capped at 80
  mutate_at(vars(pid7:aid_minorities), ~recode(., is_negative, NA_real_)) |>
  mutate_at(vars(gender:aid_minorities), ~recode(., \(x) (x >= 90), NA_real_))

anes20 <- anes20 |>
  mutate(
    dem = pid7 %in% 1:3,
    rep = pid7 %in% 5:7,
    # code has both definitions of `ind`, commented-out one is never used though
    # previous mutate_at call has already recoded 99s to NA, explicitly remove
    # pid7 from vars() if you want to change this
    ind = pid7 %in% c(4, 99),
    # ind = pid7 == 4,
    # regardless of coding decision, pid7 needs 99s recoded later
    # for constructing Mason sorting variables
    pid7 = case_when(pid7 >= 90 ~ 4, TRUE ~ pid7),
    ideo = case_when(ideo >= 90 ~ 4, TRUE ~ ideo),
    #ideo = reverse_code(ideo),
    male = gender == 1,
    female = gender == 2,
    white = race == 1,
    black = race == 2,
    asian = race == 4,
    nativeamerican = race == 5,
    multiracial = race == 6,
    hisp = race == 3, # TODO: are these the right race/ethnicity codings?
    union = union == 1,
    age_18 = age %in% 18:29,
    age_30 = age %in% 30:44,
    age_45 = age %in% 45:64,
    age_65 = age > 65,
    urban = rural_identity == 1,
    suburb = rural_identity == 2,
    smalltown = rural_identity == 3,
    rural = rural_identity == 4,
    evang = evang %in% c(2, 3),
    military = military %in% c(1, 2),
    gun = num_guns > 0,
    lowerclass = class == 1,
    workingclass = class == 2,
    middleclass = class == 3,
    upperclass = class == 4,
    lessHS = education == 1,
    HS = education == 2,
    somecollege = education == 3,
    college = education == 4,
    graduate = education == 5,
    bothparentsUS = parental_origin == 1,
    oneparentUS = parental_origin == 2,
    bothparentsnotUS = parental_origin == 3,
    income25K = income %in% 1:4,
    income50K = income %in% 5:9,
    income75K = income %in% 10:13,
    income100K = income %in% 14:16,
    income150K = income %in% 17:19,
    income250K = income %in% 20:21,
    incomemore250K = income == 22,
    married = marital_status %in% 1:2,
    single = marital_status %in% 3:6,
    straight = sexual_orientation == 1,
    gay = sexual_orientation == 2,
    bi = sexual_orientation == 3,
    children = num_children > 0,
    RR_favor = reverse_code(RR_favor),
    RR_try = reverse_code(RR_try),
    RR = (RR_favor + RR_gen + RR_less + RR_try) / 4,
    RR1 = RR <= quantile(RR, probs = 0.3333, na.rm = TRUE),
    RR2 = RR <= quantile(RR, probs = 0.6666, na.rm = TRUE),
    RR3 = RR >= quantile(RR, probs = 0.6666, na.rm = TRUE),
    auth1 = auth1 == 2,
    auth2 = auth2 == 2,
    auth3 = auth3 == 1,
    auth4 = auth4 == 2,
    AUTH = auth1 + auth2 + auth3 + auth4,
    AUTH1 = AUTH <= quantile(AUTH, probs = 0.3333, na.rm = TRUE),
    AUTH2 = AUTH <= quantile(AUTH, probs = 0.6666, na.rm = TRUE),
    AUTH3 = AUTH >= quantile(AUTH, probs = 0.6666, na.rm = TRUE),
    egal1 = reverse_code(egal1),
    egal4 = reverse_code(egal4),
    EGAL = egal1 + egal2 + egal3 + egal4,
    sexism2 = reverse_code(sexism2),
    sexism3 = reverse_code(sexism3),
    sexism4 = reverse_code(sexism4),
    # NOTE: sexism1 is a 7-point likert scale, but others are 5-point;
    # shouldn't they be weighted differently?
    SEXISM = (sexism1 + sexism2 + sexism3 + sexism4) / 4,
    # NOTE: same thing - are nationalism itmes on the same scale?
    nat1 = reverse_code(nat1),
    nat2 = reverse_code(nat2),
    nat3 = reverse_code(nat3),
    nat4 = reverse_code(nat4),
    nat5 = reverse_code(nat5),
    nat6 = reverse_code(nat6),
    NAT = pmap_dbl(list(nat1, nat2, nat3, nat4, nat5, nat6),
                  \(...) (mean(c(...), na.rm = FALSE))),
    NAT2.1 = pmap_dbl(list(nat1, nat2, nat5, nat6),
                  \(...) (mean(c(...), na.rm = FALSE))),
    NAT2.2 = pmap_dbl(list(nat3, nat4),
                  \(...) (mean(c(...), na.rm = FALSE))),
    mortrad2 = reverse_code(mortrad2),
    fb_political = reverse_code(fb_political),
    tw_political = reverse_code(tw_political),
    #TODO: rd_political NAs need recoding
    rd_political = reverse_code(rd_political),
    sm_political = pmap_dbl(list(fb_political, tw_political, rd_political),
                            \(...) (mean(c(...), na.rm = TRUE))),
    # NOTE: these variables are specific shows, return 1 if any are mentioned,
    # 0 otherwise
    # NOTE: what should na.rm be here? ethan has F
    news_fox = pmap_dbl(list(hannity, tucker, the_five, ingraham,
                             maccallum, baier, fox_and_friends),
                        \(...) (max(c(0, ...), na.rm = TRUE))),
    news_msnbc = pmap_dbl(list(maddow, lawrence, morning_joe,
                               chris_hayes, brian_williams),
                          \(...) (max(c(0, ...), na.rm = TRUE))),
    news_cnn = pmap_dbl(list(tapper, anderson, cuomo, erin_burnett),
                        \(...) (max(c(0, ...), na.rm = TRUE))),
    # NOTE: ethan has coded Refused as 0, should that be NA?
    know_senateterm = know_senateterm == 6,
    know_spend = know_spend == 1,
    know_house = know_house == 1,
    know_senate = know_senate == 2,
    know_scale = pmap_dbl(list(know_senateterm, know_spend,
                               know_house, know_senate),
                          \(...) (mean(c(...), na.rm = TRUE))),
    pid7_str = abs(pid7 - 4) + 1,
    ideo_str = abs(ideo - 4) + 1,
    pidideostr1 = pid7_str * ideo_str,
    overlap = abs(pid7 - ideo) + 1,
    overlap_rr =  reverse_code(overlap),
    overlapxstr = overlap_rr * pidideostr1,
    sorting_r = (overlapxstr - 7) / 105,
    # NOTE: these two variables are identical
    vio_justy = vio_justscale > 1,
    viojustbi = vio_justscale > 1,
    violence1 = violence / 5,
    # NOTE: i think line 775 in ethan's code should have been
    # commented out, and am ignoring it
    unrest = case_when(unrest == 99 ~ NA_real_, TRUE ~ unrest),
    unrest1 = unrest / 7,
    unrestbi = unrest > 4,
    fairelecbi = fairelec > 3,
    # NOTE: double check `educ` vs `education`
    # educ = case_when(educ == 95 ~ NA_real_, TRUE ~ educ),
    comp1.1 = reverse_code(comp1) / 5,
    comp2.1 = comp2 == 2,
    joinprotest = joined025 == 1,
    commiss = community == 1,
    conoff = contact034 == 1,
    talk109 = talk009 == 1,
    attend113 = attend013 == 1,
    attend114 = attend014 == 1,
    wear115 = wear015 == 1,
    work116 = work016 == 1,
    give117 = give017 == 1,
    give119 = give019 == 1,
    contact130 = contact030 == 1,
    contact134 = contact034 == 1,
    contact136 = contact036 == 1,
    give138 = give038 == 1,
    contact140 = contact040 == 1,
    joined125 = joined025 == 1,
    signed126 = signed026 == 1,
    bought142 = bought042 == 1,
    discuss122 = discuss022 == 1,
    posted129 = posted029 == 1,
    OVERALLINDEX1 = pmap_dbl(list(talk109, attend113, attend114, wear115,
                                  work116, give117, give119, contact130,
                                  contact134, contact136, give138, contact140,
                                  joined125, signed126, bought142, discuss122,
                                  posted129),
                             \(...) (mean(c(...), na.rm = FALSE))),
    SYSTEMICINDEX1 = pmap_dbl(list(talk109, attend113, attend114, wear115,
                                   work116, give117, give119, contact130,
                                   contact134, contact136, give138, contact140),
                              \(...) (mean(c(...), na.rm = FALSE))),
    NONSYSTEMICINDEX1 = pmap_dbl(list(joined125, signed126, bought142,
                                      discuss122, posted129),
                                 \(...) (mean(c(...), na.rm = FALSE))),
    MASONINDEX1 = pmap_dbl(list(talk109, wear115, give117,
                           joined125, work116),
                           \(...) (mean(c(...), na.rm = FALSE))),
    # NOTE: why is this only defined for non-independents?
    # disregarding for now, because I think it breaks one of
    # the regression models later on.
    # ftdifference = case_when(ind == 0 ~ abs(FT_dem - FT_rep), TRUE ~ NA_real),
    ftdifference = abs(FT_dem - FT_rep),
    ftdifference_mason = ftdifference / 100,
    # NOTE: i need to think through what these values mean
    religscale = case_when(
      is.na(attend_church_ever) ~ NA_real_,
      attend_church_ever == 2 ~ 0,
      attend_church_more == 1 ~ 1,
      TRUE ~ reverse_code(attend_church) / 5
    ),
    attend_church_ever = reverse_code(attend_church_ever),
    bornagain = bornagain == 1,
    dem1 = case_when(
      dem1 == 1 ~ 0,
      dem1 == 2 ~ 0.333,
      dem1 == 4 ~ 0.666,
      dem1 == 5 ~ 1,
      TRUE ~ NA_real_,
    ),
    dem2 = dem2 / 5,
    # NOTE: very slight divergence from ethan's code here re: rounding
    dem3 = round(dem3 / 7, 2),
    demsupport = pmap_dbl(list(dem1, dem2, dem3),
                          \(...) (mean(c(...), na.rm = FALSE))),
    south = state %in% c("AL", "AR", "FL", "GA", "LA", "MS",
                         "NC", "SC", "TN", "TX", "VA"),
    # reverse code issue positions to align
    insurance = reverse_code(insurance),
    defense = reverse_code(defense),
    employment = reverse_code(employment),
    aid_minorities = reverse_code(aid_minorities),
    # create the strength indices, then rescale the policy variables
    abortion_str = as.integer(abortion %in% c(1, 4)),
    insurance_str = abs(insurance - 4) / 3,
    services_str = abs(services - 4) / 3,
    employment_str = abs(employment - 4) / 3,
    aid_minorities_str = abs(aid_minorities - 4) / 3,
    defense_str = abs(defense - 4) / 3,
    abortion = abortion / max(abortion, na.rm = T),
    insurance = insurance / max(insurance, na.rm = T),
    defense = defense / max(defense, na.rm = T),
    services = services / max(services, na.rm = T),
    employment = employment / max(employment, na.rm = T),
    aid_minorities = aid_minorities / max(aid_minorities, na.rm = T),
    policyindex = pmap_dbl(list(abortion, insurance, services,
                                defense, employment, aid_minorities),
                           \(...) (mean(c(...), na.rm = TRUE))),
    issue_strength = pmap_dbl(list(abortion_str, insurance_str, services_str,
                                   aid_minorities_str, employment_str, defense_str),
                              \(...) (mean(c(...), na.rm = TRUE))),
    issue_constraint = pmap_dbl(list(abortion_str, insurance_str, services_str,
                                     aid_minorities_str, employment_str, defense_str),
                                \(...) (sd(c(...), na.rm = TRUE))),
    # policyindex = (abortion / 4 + reverse_code(insurance) / 7 +
    #               services / 7 + reverse_code(defense) / 7 +
    #               reverse_code(defense) / 7 + reverse_code(aid_minorities) / 7) / 6,
    # Mason replication models want PID reverse coded
    pid7_mason = reverse_code(pid7) / 7,
    pid7_str_mason = pid7_str / 4,
    # we wrote a bunch of these as pure boolean statements, but we
    # actually want 0/1s, so now recode all of those T/Fs at once
  ) |> mutate_if(is_logical, as.numeric)


# 2016 ANES ---------------------------------------------------------------


anes16 <- anes16 |>
  select(
    id = V160202,
    panel_id = V160001_orig,
    strata = V160201,
    weight = V160101,
    pid7 = V161158x,
    ideo = V162171,
    gender = V161342,
    race = V161310x,
    ethnicity = V161309,
    evang = V161266d,
    military = V161274a,
    union = V161302,
    age = V161267,
    num_guns = V161496,
    # TODO: has the coding of this variable changed from 2020?
    class = V162132,
    education = V161270,
    parental_origin = V161315,
    income = V161361x,
    marital_status = V161268,
    sexual_orientation = V161511,
    num_children = V161324,
    # TODO: has the coding of this variable changed from 2020?
    RR_gen = V162212,
    RR_favor = V162211,
    RR_less = V162213,
    RR_try = V162214,
    auth1 = V162239,
    auth2 = V162240,
    auth3 = V162241,
    auth4 = V162242,
    egal1 = V162243,
    egal2 = V162244,
    egal3 = V162245,
    egal4 = V162246,
    sexism1 = V162229x,
    sexism2 = V162230x,
    sexism3 = V162232,
    sexism4 = V162233,
    nat1 = V162123,
    nat3 = V162271,
    nat4 = V162272,
    nat5 = V162273,
    nat6 = V162274,
    mortrad1 = V162207,
    mortrad2 = V162210,
    facebook_tw = V161495,
    # NOTE: different set of TV shows to work on than 2020
    twenty_twenty = V161364,
    chris_hayes = V161365,
    blacklist = V161366,
    cbs_evening = V161367,
    criminal_minds = V161368,
    empire = V161369,
    hannity = V161370,
    kimmel = V161371,
    kelly = V161372,
    modern_family = V161373,
    ncis = V161374,
    wilmore = V161375,
    sunday_night_football = V161376,
    scorpion = V161377,
    simpsons = V161378,
    today = V161379,
    sixty_minutes = V161380,
    anderson = V161381,
    cbs_this_morning = V161382,
    dancing_with_the_stars = V161383,
    face_the_nation = V161384,
    house_of_cards = V161385,
    chris_matthews = V161386,
    judge_judy = V161387,
    meet_the_press = V161388,
    game_of_thrones = V161389,
    nbc_nightly = V161390,
    van_susteren = V161391,
    daredevil = V161392,
    maddow = V161393,
    shark_tank = V161394,
    the_voice = V161395,
    abc_world = V161396,
    blue_bloods = V161397,
    conan = V161398,
    dateline = V161399,
    gma = V161400,
    hawaii_five_o = V161401,
    madam_secretary = V161402,
    nancy_grace = V161403,
    erin_burnett = V161404,
    newshour = V161405,
    scandal = V161406,
    big_bang = V161407,
    colbert = V161408,
    oreilly = V161409,
    fallon = V161410,
    cnn_en_espanol = V161415,
    know_senateterm = V161513,
    know_spend = V161514,
    know_house = V161515,
    know_senate = V161516,
    vio_justscale = V161344,
    fairelec = V162219,
    demsat = V162290,
    compprinc = V161171,
    comp1 = V162259,
    comp2 = V161171,
    community = V162195,
    talk009 = V162010,
    attend014 = V162011,
    wear015 = V162012,
    work016 = V162013,
    give017 = V162014,
    give019 = V162016,
    contact030 = V162019,
    contact034 = V162198,
    contact036 = V162200,
    give038 = V162202,
    contact040 = V162204,
    joined025 = V162018a,
    signed026 = V162018b,
    bought042 = V162141,
    discuss022 = V162174,
    FT_dem = V161095,
    FT_rep = V161096,
    attend_church_ever = V161244,
    attend_church = V161245,
    attend_church_more = V161245a,
    bornagain = V161263,
    dem1 = V162290,
    abortion = V161232,
    insurance = V161184,
    services = V161178,
    defense = V161181,
    employment = V161189,
    aid_minorities = V161198,
    state = V161010e,
    # NOTE: coded differently in 2016 than other years, absent in 2020
    anger_dem = V161116,
    anger_rep = V161121,
  ) |>
  mutate_at(vars(pid7:aid_minorities), ~recode(., is_negative, NA_real_)) |>
  # NOTE: this is not being applied to pid7 or ideo
  mutate_at(vars(gender:aid_minorities), ~recode(., \(x) (x >= 90), NA_real_))


anes16 <- anes16 |>
  mutate(
    dem = pid7 %in% 1:3,
    rep = pid7 %in% 5:7,
    # NOTE: see discuss of coding of `ind` in anes20
    ind = pid7 %in% c(4, 99),
    # recode 99s to 4s (DK/Refuse to moderate)
    pid7 = case_when(pid7 >= 90 ~ 4, TRUE ~ pid7),
    ideo = case_when(ideo >= 90 ~ 4, TRUE ~ ideo),
    #ideo = reverse_code(ideo),
    male = gender == 1,
    female = gender == 2,
    white = race == 1,
    black = race == 2,
    asian = race == 3,
    nativeamerican = race == 4,
    multiracial = race == 6,
    hisp = race == 5,
    union = union == 1,
    age_18 = age %in% 18:29,
    age_30 = age %in% 30:44,
    age_45 = age %in% 45:64,
    age_65 = age > 65,
    evang = evang %in% c(2, 3),
    military = military %in% c(1, 2),
    gun = num_guns > 0,
    lowerclass = class == 1,
    workingclass = class == 2,
    middleclass = class == 3,
    upperclass = class == 4,
    lessHS = education == 1,
    HS = education == 2,
    somecollege = education == 3,
    college = education == 4,
    graduate = education == 5,
    bothparentsUS = parental_origin == 1,
    oneparentUS = parental_origin == 2,
    bothparentsnotUS = parental_origin == 3,
    income25K = income %in% 1:4,
    income50K = income %in% 5:9,
    income75K = income %in% 10:13,
    income100K = income %in% 14:16,
    income150K = income %in% 17:19,
    income250K = income %in% 20:21,
    incomemore250K = income == 22,
    married = marital_status %in% 1:2,
    single = marital_status %in% 3:6,
    straight = sexual_orientation == 1,
    gay = sexual_orientation == 2,
    bi = sexual_orientation == 3,
    children = num_children > 0,
    RR_favor = reverse_code(RR_favor),
    RR_try = reverse_code(RR_try),
    RR = (RR_favor + RR_gen + RR_less + RR_try) / 4,
    RR1 = RR <= quantile(RR, probs = 0.3333, na.rm = TRUE),
    RR2 = RR <= quantile(RR, probs = 0.6666, na.rm = TRUE),
    RR3 = RR >= quantile(RR, probs = 0.6666, na.rm = TRUE),
    auth1 = auth1 == 2,
    auth2 = auth2 == 2,
    auth3 = auth3 == 1,
    auth4 = auth4 == 2,
    AUTH = auth1 + auth2 + auth3 + auth4,
    AUTH1 = AUTH <= quantile(AUTH, probs = 0.3333, na.rm = TRUE),
    AUTH2 = AUTH <= quantile(AUTH, probs = 0.6666, na.rm = TRUE),
    AUTH3 = AUTH >= quantile(AUTH, probs = 0.6666, na.rm = TRUE),
    egal1 = reverse_code(egal1),
    egal4 = reverse_code(egal4),
    EGAL = egal1 + egal2 + egal3 + egal4,
    sexism2 = reverse_code(sexism2),
    sexism3 = reverse_code(sexism3),
    sexism4 = reverse_code(sexism4),
    # NOTE: sexism1 is a 7-point likert scale, but others are 5-point;
    # shouldn't they be weighted differently?
    SEXISM = (sexism1 + sexism2 + sexism3 + sexism4) / 4,
    # NOTE: same thing - are nationalism itmes on the same scale?
    nat1 = reverse_code(nat1),
    nat3 = reverse_code(nat3),
    nat4 = reverse_code(nat4),
    nat5 = reverse_code(nat5),
    nat6 = reverse_code(nat6),
    NAT = pmap_dbl(list(nat1, nat3, nat4, nat5, nat6),
                   \(...) (mean(c(...), na.rm = FALSE))),
    NAT2.1 = pmap_dbl(list(nat1, nat5, nat6),
                      \(...) (mean(c(...), na.rm = FALSE))),
    NAT2.2 = pmap_dbl(list(nat3, nat4),
                      \(...) (mean(c(...), na.rm = FALSE))),
    mortrad2 = reverse_code(mortrad2),
    news_fox = pmap_dbl(list(hannity, kelly, van_susteren, oreilly),
                        \(...) (max(c(0, ...), na.rm = TRUE))),
    news_msnbc = pmap_dbl(list(chris_matthews, maddow),
                          \(...) (max(c(0, ...), na.rm = TRUE))),
    news_cnn = pmap_dbl(list(anderson, nancy_grace,
                             erin_burnett, cnn_en_espanol),
                        \(...) (max(c(0, ...), na.rm = TRUE))),
    # NOTE: ethan has coded Refused as 0, should that be NA?
    # TODO: double-check the answers in 2016 are the same as 2020
    know_senateterm = know_senateterm == 6,
    know_spend = know_spend == 1,
    know_house = know_house == 1,
    know_senate = know_senate == 2,
    know_scale = pmap_dbl(list(know_senateterm, know_spend,
                               know_house, know_senate),
                          \(...) (mean(c(...), na.rm = TRUE))),
    pid7_str = abs(pid7 - 4) + 1,
    pid7_str_mason = pid7_str / 4,
    ideo_str = abs(ideo - 4) + 1,
    pidideostr1 = pid7_str * ideo_str,
    overlap = abs(pid7 - ideo) + 1,
    overlap_rr =  reverse_code(overlap),
    overlapxstr = overlap_rr * pidideostr1,
    sorting_r = (overlapxstr - 7) / 105,
    # NOTE: these two variables are identical
    vio_justy = vio_justscale > 1,
    viojustbi = vio_justscale > 1,
    fairelecbi = fairelec > 3,
    # TODO: resolve educ v. education
    # educ = case_when(educ == 95 ~ NA_real_, TRUE ~ educ),
    comp1.1 = reverse_code(comp1) / 5,
    comp2.1 = comp2 == 2,
    joinprotest = joined025 == 1,
    commiss = community == 1,
    conoff = contact034 == 1,
    talk109 = talk009 == 1,
    attend114 = attend014 == 1,
    wear115 = wear015 == 1,
    work116 = work016 == 1,
    give117 = give017 == 1,
    give119 = give019 == 1,
    contact130 = contact030 == 1,
    contact134 = contact034 == 1,
    contact136 = contact036 == 1,
    give138 = give038 == 1,
    contact140 = contact040 == 1,
    joined125 = joined025 == 1,
    signed126 = signed026 == 1,
    bought142 = bought042 == 1,
    discuss122 = discuss022 == 1,
    OVERALLINDEX1 = pmap_dbl(list(talk109, attend114, wear115, work116,
                                  give117, give119, contact130, contact134,
                                  contact136, give138, contact140, joined125,
                                  signed126, bought142, discuss122),
                             \(...) (mean(c(...), na.rm = FALSE))),
    SYSTEMICINDEX1 = pmap_dbl(list(talk109, attend114, wear115, work116,
                                   give117, give119, contact130, contact134,
                                   contact136, give138, contact140),
                              \(...) (mean(c(...), na.rm = FALSE))),
    NONSYSTEMICINDEX1 = pmap_dbl(list(joined125, signed126,
                                      bought142, discuss122),
                                \(...) (mean(c(...), na.rm = FALSE))),
    MASONINDEX1 = pmap_dbl(list(talk109, wear115, give117,
                                joined125, work116),
                           \(...) (mean(c(...), na.rm = FALSE))),
    # NOTE: see discussion of variable change in anes20
    ftdifference = abs(FT_dem - FT_rep),
    ftdifference_mason = ftdifference / 100,
    religscale = case_when(
      is.na(attend_church_ever) ~ NA_real_,
      attend_church_ever == 2 ~ 0,
      attend_church_more == 1 ~ 1,
      TRUE ~ reverse_code(attend_church) / 5
    ),
    attend_church_ever = reverse_code(attend_church_ever),
    bornagain = bornagain == 1,
    dem1 = case_when(
      dem1 == 1 ~ 0,
      dem1 == 2 ~ 0.333,
      dem1 == 4 ~ 0.666,
      dem1 == 5 ~ 1,
      TRUE ~ NA_real_,
    ),
    south = state %in% c("AL", "AR", "FL", "GA", "LA", "MS",
                         "NC", "SC", "TN", "TX", "VA"),
    # policyindex = (abortion / 4 + reverse_code(insurance) / 7 +
    #               services / 7 + reverse_code(defense) / 7 +
    #               reverse_code(defense) / 7 + reverse_code(aid_minorities) / 7) / 6,
    # reverse code issue positions to align
    insurance = reverse_code(insurance),
    defense = reverse_code(defense),
    employment = reverse_code(employment),
    aid_minorities = reverse_code(aid_minorities),
    # create the strength indices, then rescale the policy variables
    abortion_str = as.integer(abortion %in% c(1, 4)),
    insurance_str = abs(insurance - 4) / 3,
    services_str = abs(services - 4) / 3,
    employment_str = abs(employment - 4) / 3,
    aid_minorities_str = abs(aid_minorities - 4) / 3,
    defense_str = abs(defense - 4) / 3,
    abortion = abortion / max(abortion, na.rm = T),
    insurance = insurance / max(insurance, na.rm = T),
    defense = defense / max(defense, na.rm = T),
    services = services / max(services, na.rm = T),
    employment = employment / max(employment, na.rm = T),
    aid_minorities = aid_minorities / max(aid_minorities, na.rm = T),
    policyindex = pmap_dbl(list(abortion, insurance, services,
                                defense, employment, aid_minorities),
                           \(...) (mean(c(...), na.rm = TRUE))),
    issue_strength = pmap_dbl(list(abortion_str, insurance_str, services_str,
                                   aid_minorities_str, employment_str, defense_str),
                              \(...) (mean(c(...), na.rm = TRUE))),
    issue_constraint = pmap_dbl(list(abortion_str, insurance_str, services_str,
                                     aid_minorities_str, employment_str, defense_str),
                                \(...) (sd(c(...), na.rm = TRUE))),
    # Mason replication models want PID reverse coded
    # pid7 = reverse_code(pid7),
    anger_outpartisan = pmap_dbl(list(dem, rep, anger_dem, anger_rep),
                                 \(d, r, ad, ar) case_when(d == TRUE ~ ar, r == TRUE ~ ad, TRUE ~ NA_integer_)),
    #anger_outpartisan = anger_outpartisan == 1
    ) |> mutate_if(is_logical, as.numeric)


# ANES panel ----------------------------------------------------------------
# NOTE: these variable names _are_ different (.x, .y is too confusing for me)

panel <- inner_join(anes20, anes16, by = "panel_id", suffix=c("_2020", "_2016"))
panel$panel <- as.numeric(panel$sample_type == 2)
panel <- panel |> mutate(
  ftdifference_change = ftdifference_2020 - ftdifference_2016,
  MASONINDEX1_change = MASONINDEX1_2020 - MASONINDEX1_2016,
  comp1.1_change = comp1.1_2020 - comp1.1_2016,
  comp2.1_change = comp2.1_2020 - comp2.1_2016,
  vio_justy_change = vio_justy_2020 - vio_justy_2016,
  fairelec_change = fairelec_2020 - fairelec_2016,
  demsat_change = demsat_2020 - demsat_2016,
  sorting_r_change = sorting_r_2020 - sorting_r_2016,
  AUTH_change = AUTH_2020 - AUTH_2016,
  RR_change = RR_2020 - RR_2016
)


# 2012 ANES ---------------------------------------------------------------

anes12 <- anes12 |>
  select(
    id = caseid,
    weight = weight_full,
    strata = strata_full,
    pid7 = pid_x,
    ideo = libcpo_self, # NOTE: double-check. seems weird that PID is pre and ideo is post.
    race = dem_raceeth_x,  # not split out into race/eth? other race questions are FTF only?
    educ = dem_edu,
    age = dem_age_r_x,
    gender = gender_respondent_x,
    # urban = dwell_block_urban,  # NOTE: this does not seem to be self-ID
    # Mason policy index: abortion, government services versus spending,
    # government health insurance, aid to minorities, employment protections,
    # defense spending
    abortion = abortpre_4point, # lib high
    insurance = inspre_self, # con high
    services = spsrvpr_ssself, # lib high
    defense = defsppr_self, # lib low
    employment = guarpr_self,  # con high
    aid_minorities = aidblack_self, # con high
    # TODO: align with attend_church_* for 2016/2020 ANES
    attend_church_ever = relig_church,
    FT_dem = ft_dem,
    FT_rep = ft_rep,
    state = sample_state,
    know_senateterm = preknow_senterm,
    know_spend = preknow_leastsp,
    income = incgroup_prepost_x,
    #know_house = V201646,
    #know_senate = V201647,
    anger_rep = candaff_angrpc,
    anger_dem = candaff_angdpc,
  ) |>
  mutate_if(is.numeric, ~recode(., is_negative, NA_real_)) |>
  mutate_at(vars(id:attend_church_ever), ~recode(., \(x) (x >= 90), NA_real_)) |>
  mutate(
    dem = pid7 %in% 1:3,
    rep = pid7 %in% 5:7,
    # NOTE: see discuss of coding of `ind` in anes20
    ind = pid7 %in% c(4, 99),
    # pid7 = reverse_code(pid7),
    #ideo = reverse_code(ideo),
    # NOTE: "Political South" not "Census South"
    south = state %in% c("AL", "AR", "FL", "GA", "LA", "MS",
                         "NC", "SC", "TN", "TX", "VA"),
    white = race == 1,
    black = race == 2,
    asian = race == 3,
    nativeamerican = race == 4,
    hisp = race == 5,
    #  urban = urban == 4,
    male = gender == 1,
    female = gender == 2,
    attend_church_ever = reverse_code(attend_church_ever),
    educ = case_when(
      educ %in% 1:4 ~ 1,
      educ %in% 5:8 ~ 2,
      educ == 9 ~ 3,
      educ %in% 10:12 ~ 5,
      educ == 13 ~ 6,
      educ %in% 14:16 ~ 7,
      TRUE ~ NA_real_
    ),
    # reverse code issue positions to align
    insurance = reverse_code(insurance),
    defense = reverse_code(defense),
    employment = reverse_code(employment),
    aid_minorities = reverse_code(aid_minorities),
    # create the strength indices, then rescale the policy variables
    abortion_str = as.integer(abortion %in% c(1, 4)),
    insurance_str = abs(insurance - 4) / 3,
    services_str = abs(services - 4) / 3,
    employment_str = abs(employment - 4) / 3,
    aid_minorities_str = abs(aid_minorities - 4) / 3,
    defense_str = abs(defense - 4) / 3,
    abortion = abortion / max(abortion, na.rm = T),
    insurance = insurance / max(insurance, na.rm = T),
    defense = defense / max(defense, na.rm = T),
    services = services / max(services, na.rm = T),
    employment = employment / max(employment, na.rm = T),
    aid_minorities = aid_minorities / max(aid_minorities, na.rm = T),
    policyindex = pmap_dbl(list(abortion, insurance, services,
                                defense, employment, aid_minorities),
                           \(...) (mean(c(...), na.rm = TRUE))),
    issue_strength = pmap_dbl(list(abortion_str, insurance_str, services_str,
                                   aid_minorities_str, employment_str, defense_str),
                              \(...) (mean(c(...), na.rm = TRUE))),
    issue_constraint = pmap_dbl(list(abortion_str, insurance_str, services_str,
                                   aid_minorities_str, employment_str, defense_str),
                              \(...) (sd(c(...), na.rm = TRUE))),
    pid7_str = abs(pid7 - 4) + 1,
    ideo_str = abs(ideo - 4) + 1,
    pidideostr1 = pid7_str * ideo_str,
    overlap = abs(pid7 - ideo) + 1,
    overlap_rr =  reverse_code(overlap),
    overlapxstr = overlap_rr * pidideostr1,
    sorting_r = (overlapxstr - 7) / 105,
    # NOTE: ANES 2012 only has two of the knowledge measures we were using from
    #       2016/2020. There are others we could draw on but for now we'll just
    #       use those two.
    know_senateterm = know_senateterm == 6,
    know_spend = know_spend == 1,
    know_scale = pmap_dbl(list(know_senateterm, know_spend),
                          \(...) (mean(c(...), na.rm = TRUE))),
    ftdifference = abs(FT_dem - FT_rep),
    ftdifference_mason = ftdifference / 100,
    pid7_str_mason = pid7_str / 4,
    # anger_outpartisan = case_when(
    #   dem == TRUE ~ anger_rep,
    #   rep == TRUE ~ anger_dem,
    #   TRUE ~ NA_integer_
    # ),
    anger_outpartisan = pmap_dbl(list(dem, rep, anger_dem, anger_rep),
                                 \(d, r, ad, ar) case_when(d == TRUE ~ ar, r == TRUE ~ ad, TRUE ~ NA_integer_)),
    anger_outpartisan = anger_outpartisan == 1
  ) |> mutate_if(is_logical, as.numeric)


# Output ------------------------------------------------------------------


# write out my updated version. this also contains the original data
save.image("data/stefan_sorting_data.RData")
